In [2]:
import numpy as np
a=[[1,4,6],[3,5,6]]

In [3]:
a

[[1, 4, 6], [3, 5, 6]]

In [5]:
a = np.array([[2,4,5],[4,3,5],[4,6,8]])

In [6]:
a.shape

(3, 3)

In [7]:
a.size

9

In [8]:
a

array([[2, 4, 5],
       [4, 3, 5],
       [4, 6, 8]])

In [9]:
np.var(a)

2.691358024691358

In [10]:
np.std(a)


1.640535895581489

In [11]:
np.max(a)

8

In [15]:
np.min(a)
np.max(a,axis=0)

array([4, 6, 8])

In [16]:
np.cumsum(a)

array([ 2,  6, 11, 15, 18, 23, 27, 33, 41])

In [25]:
np.cumsum(a,axis=-1)

array([[ 2,  6, 11],
       [ 4,  7, 12],
       [ 4, 10, 18]])

In [29]:
np.argmin(a)

0